version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # image: especializati/laravel9-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    # nginx
    nginx:
        image: nginx:alpine
        ports: 
            - "${APP_PORT}:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9

    # db mysql
    mysql:
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "${DB_FORWARD_PORT}:${DB_PORT}"
        networks:
            - laravel-9

    # queue
    queue:
        image: especializati/laravel9-app
        command: 
            - "php artisan queue:work"
            - "php artisan watermark:users"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-9

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel-9

    #mailhog
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'  #disable saving logs
        ports:
            - "${MAILHOG_SMTP_PORT}:1025"   #smtp server
            - "${MAILHOG_WEB_PORT}:8025"    #web ui
        networks:
            - laravel-9

networks:
    laravel-9:
        driver: bridge
